<script>
    const TIMEOUT = 3000;
    
    import { connected, createSocket } from '$lib/services/SocketIOClient.js';
	import { onMount } from 'svelte';
    import { fly, fade } from 'svelte/transition';
    import { submitFormData } from "$lib/services/SocketIOClient.js"

	onMount(async () => {
		createSocket();
	});

    let { data } = $props();
    let checked = $state(false);
    let name = $state('');
    let submitted = $state(false);
    let showModal = $state(false);


    function submitForm() {
        console.log('submitting form');
        data = {name: name};
        submitFormData(data);
        submitted = true;

        setTimeout(() => {
            submitted = false;
            name = '';
            checked = false;
        }, TIMEOUT);
    }

</script>


{#if $connected}
    {#if !submitted}
        <div class="container" in:fade={{ duration: 1000 }}>
            <div>
                <img src="/finalLogo_Black.png" alt="" class="logo">
            </div>
            <h1>Welcome to WaveCaster™ Entertainment Labs!</h1>
            <p>To sign up for the beta testing program please fill out the form, and read our terms and conditions.</p>
            <form>
                <label for="fname">First Name</label><br>
                <input bind:value={name} type="text" id="fname" name="fname" required><br>
                <div class="checkbox-container">
                    <input type="checkbox" bind:checked={checked} id="terms" required>
                    <label for="terms">I hereby confirm that I have read, understood and accepted <a href="" onclick={() => {showModal = true}} style="color: #00d4a9;">the terms and conditions</a>.</label>
                </div>
                <button disabled={!(name && checked)} type="submit" class="button" onclick={submitForm}>Sign up ➜</button>
                
            </form>
        </div>
    {:else}
        <div class="container2" in:fly={{ y: 200, duration: 2000 }}>
            <img src="/arrow.svg" alt="">
            <h1 in:fly={{ y: 200, duration: 3000 }}>Thank you for being so generous with your data!</h1>
        </div>
    {/if}
    
{:else}
	<div class="error-wrapper">
		<h1>-.-</h1>
		<p>No Connection</p>
	</div>
{/if}

{#if showModal}
    <div class="modal-backdrop" onclick={()=>{showModal = false}}></div>
    <div class="modal">
        <div class="modal-content">
            <div class="grid-cols-1 grid gap-2.5 [&amp;_>_*]:min-w-0"><p class="whitespace-pre-wrap break-words">WAVECASTER™ ENTERTAINMENT - BETA TESTING AGREEMENT AND TERMS OF SERVICE
                Version 4.2.1 (February 2025)</p>
                <ol class="[&amp;:not(:last-child)_ul]:pb-1 [&amp;:not(:last-child)_ol]:pb-1 list-decimal space-y-1.5 pl-7" depth="0">
                <li class="whitespace-normal break-words" index="0">DEFINITIONS
                1.1 "Experience" refers to any sensory, emotional, physiological, or cognitive interaction within the WaveCaster™ Concert Lab environment.
                1.2 "Biometric Response Data" encompasses, but is not limited to, emotional reactions, neural responses, cardiovascular patterns, and endocrine fluctuations as further detailed in Section 7.3.
                1.3 "Participant" refers to you, the Beta Tester, including your physical presence, digital shadow, and metaphysical essence (see Section 12.4).</li>
                <li class="whitespace-normal break-words" index="1">CONFIDENTIALITY AND NON-DISCLOSURE
                2.1 By entering the Experience, Participant acknowledges that everything they think they might see, hear, feel, dream about, or imagine during or after the Experience is strictly confidential as per Section 15.8.
                2.2 The obligation of confidentiality extends to alternate realities, parallel dimensions, and any quantum states the Participant may occupy during the Experience (reference Appendix C-7).</li>
                <li class="whitespace-normal break-words" index="2">DATA COLLECTION CONSENT
                3.1 Participant grants WaveCaster™ unrestricted rights to collect, analyze, and monetize any and all data generated by their existence before, during, and after the Experience, including but not limited to:
                a) Conscious thoughts
                b) Subconscious impressions
                c) Past and future memories
                d) Genetic predispositions
                e) Emotional spectrum variations
                As further detailed in Section 9.6</li>
                <li class="whitespace-normal break-words" index="3">INTELLECTUAL PROPERTY RIGHTS
                4.1 Any creative thoughts, innovations, or dreams occurring within 50 years of the Experience automatically become property of WaveCaster™ (see Section 6.2 for temporal extensions).
                4.2 Participant's memories of the Experience are licensed to them on a non-exclusive basis, subject to revocation as per Section 11.9.</li>
                <li class="whitespace-normal break-words" index="4">LIABILITY AND INDEMNIFICATION
                5.1 WaveCaster™ assumes no responsibility for any temporal, spatial, or dimensional displacement that may occur during the Experience (see Section 8.3 for quantum entanglement exceptions).
                5.2 By participating, you waive all rights to legal recourse across all known and yet-to-be-discovered dimensions (as referenced in Section 14.2).</li>
                <li class="whitespace-normal break-words" index="5">TEMPORAL CONSIDERATIONS
                6.1 These terms apply retroactively to all past lives and proactively to future incarnations of the Participant (cross-reference with Section 17.4).
                6.2 Time-dilation effects experienced during the Experience are subject to Section 4.1.</li>
                <li class="whitespace-normal break-words" index="6">BIOMETRIC DATA COLLECTION
                7.1 Participant consents to the collection of all biometric data, including but not limited to those listed in Section 1.2.
                7.2 WaveCaster™ reserves the right to collect data from any new organs that may develop during the Experience.
                7.3 Emotional responses will be quantified, categorized, and commoditized as per Schedule B (which references back to Section 3.1).</li>
                <li class="whitespace-normal break-words" index="7">QUANTUM ENTANGLEMENT CLAUSE
                8.1 Any quantum entanglement between Participant and the Experience technology is governed by Section 5.1.
                8.2 Schrödinger's cat scenarios are covered under Appendix D-13.
                8.3 See Section 5.1 for exemptions, which in turn references this section.</li>
                <li class="whitespace-normal break-words" index="8">DATA USAGE RIGHTS
                9.1 All data collected will be used for purposes including, but not limited to, those described in Section 3.1.
                9.2 WaveCaster™ may use collected data to predict Participant's future actions in this and all parallel universes.</li>
                <li class="whitespace-normal break-words" index="9">SOUL RIGHTS AND METAPHYSICAL PROPERTIES
                10.1 Participant grants WaveCaster™ a non-exclusive lease on their soul for the duration of the Experience (see Section 1.3).
                10.2 Metaphysical properties are subject to Section 4.1 and may be referenced in future amendments to Section 6.1.</li>
                </ol>
                <p class="whitespace-pre-wrap break-words">By signing below, you acknowledge that you have read, understood, and accepted these terms, even if you haven't (as permitted by Section 13.7, which doesn't exist).</p>
                <p class="whitespace-pre-wrap break-words">Signature: _______________________
                Date: __________________________
                Quantum State: __________________</p>
                <p class="whitespace-pre-wrap break-words">Note: This agreement is legally binding in all known and unknown dimensions, including those referenced in sections that reference other sections that may or may not exist.</p></div>
            <button class="close-button" onclick={()=>{showModal = false}}>Close</button>
        </div>
    </div>
{/if}



<style>

@font-face {
    font-family: "Univers";
    src: url("/fonts/UniversRegular.ttf");
    font-style: normal;
    font-weight:normal;
}

@font-face {
    font-family: "Univers";
    src: url("/fonts/UniversBold.ttf");
    font-style:normal;
    font-weight:bold;
}
 
 

    .container, .container2 {
        max-width: 550px;
        margin: auto;
        margin-top: 80px;
        font-size: large;
    }

    img {
        width: 50%;
        margin: 0 auto;
        display: block;
    }
    
    .logo {
      width:18%;
      margin: 0 auto;
      margin-bottom: 130px;
    }

    h1 {
        font-size: 2.2rem;
        /* margin-bottom: 10px; */
        line-height: 1.25;
        font-family:"Univers";
        margin-bottom:60px;
    }

    p {
        font-family:"Univers";
        font-weight:normal;
        font-size: 1rem;
        margin-bottom:90px;
    }

    form {
        font-family:"Univers";
        font-size: 1rem;
        font-weight:normal;
        margin-top: 30px;
    }
    input[type="text"] {
        width: 90%;
        height:1rem;
        font-size:1rem;
        padding: 10px;
        margin-top: 10px;
        margin-bottom: 5px;
        background-color: rgb(23, 23, 23);
        border-radius: 5px;
        border:none;
        color:white;
    }
    .checkbox-container {
        display: flex;
        align-items: top;
        justify-content: start;
        margin-top: 60px;
        margin-bottom: 20px;
    }
    input[type="checkbox"] {
        margin-right: 10px;
        margin-left: 0px;
        width: 25px;
        height: 25px;
        accent-color:  #00d4a9;
        background-color: rgb(23, 23, 23);
       
        
       
    }
    .button {
        background-color: #00d4a9;
        color: black;
        padding: 10px 20px;
        border: none;
        cursor: pointer;
        margin-top: 20px;
        display: inline-block;
        border-radius: 5px;
    }
    .button:disabled {
        background-color: grey;
        cursor: not-allowed;
    }
    .button:not(:disabled):active {
        background-color: #008f73;
    }

    .error-wrapper {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		height: 100vh;
	}

	.error-wrapper h1 {
		font-size: 3rem;
		font-weight: normal !important;
		margin: 0;
	}

    /* Modal Styles */
    .modal-backdrop {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: rgba(0, 0, 0, 0.5);
        z-index: 10;
    }
    .modal {
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        background: rgb(25, 25, 25);
        padding: 20px;
        border-radius: 8px;
        z-index: 11;
        font-size: smaller;
        max-height: 85vh;
        overflow-y: auto;
    }
    .modal-content {
        margin-bottom: 20px;
    }
    .close-button {
        background: #00d4a9;
        color: black;
        padding: 10px 20px;
        border: none;
        cursor: pointer;
        border-radius: 5px;
    }
</style>